apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: buildctl
  name: buildctl
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: buildctl
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: buildctl
    spec:
      containers:
      - image: qiaoleibugbash.azurecr.io/buildctl
        imagePullPolicy: Always
        command: ["/bin/bash", "-c", "sleep 3600"]
        name: buildctl
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            - CHOWN
            - SETUID
            - SETGID
            - DAC_OVERRIDE
            - FOWNER
            - SETFCAP
            - AUDIT_WRITE
            - MKNOD
            - SYS_CHROOT
            - NET_RAW
            - SETPCAP
            - KILL
            - FSETID
            drop:
            - ALL
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30