name: Trigger auto deployment for hellospring-source-17

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/hellospring-source-17-AutoDeployTrigger-898dc641-f7e2-4076-bedf-8477009f4eb3.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.HELLOSPRINGSOURCE17_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: qiaoleibugbash.azurecr.io
          registryUsername: ${{ secrets.HELLOSPRINGSOURCE17_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HELLOSPRINGSOURCE17_REGISTRY_PASSWORD }}
          containerAppName: hellospring-source-17
          resourceGroup: qiaolei-bugbash-rg
          imageToBuild: qiaoleibugbash.azurecr.io/hellospring-source-17:${{ github.sha }}
          

     

